import { useAppStore } from './appStore';
import { useShallow } from 'zustand/react/shallow';

export const useAppSelectors = () => {
  return useAppStore(useShallow(s => ({
    morningUnlockedDate: s.morningUnlockedDate,
    notifications: s.notifications,
    isSyncing: s.isSyncing,
    theme: s.theme,
    addLog: s.addLog,
    addAgendaEntry: s.addAgendaEntry,
    addExam: s.addExam,
    isPassiveMode: s.isPassiveMode,
    setPassiveMode: s.setPassiveMode,
    logs: s.logs,
    setTheme: s.setTheme,
    hardReset: s.hardReset,
    trophies: s.trophies,
    unlockTrophy: s.unlockTrophy,
    addChatMessage: s.addChatMessage,
    profile: s.profile,
    chatHistory: s.chatHistory,
    activeAlerts: s.activeAlerts,
    qaSession: s.qaSession,
    setQaSession: s.setQaSession,
    updateQaAnswer: s.updateQaAnswer,
    tytSubjects: s.tytSubjects,
    aytSubjects: s.aytSubjects,
    lastCoachDirective: s.lastCoachDirective,
    setLastCoachDirective: s.setLastCoachDirective,
    hasHydrated: s.hasHydrated,
    setHasHydrated: s.setHasHydrated,
    setProfile: s.setProfile,
    isMorningBlockerEnabled: s.isMorningBlockerEnabled,
    setMorningUnlockedDate: s.setMorningUnlockedDate,
    exams: s.exams,
    eloScore: s.eloScore,
    streakDays: s.streakDays,
    setFocusSidePanelOpen: s.setFocusSidePanelOpen,
    subjectViewMode: s.subjectViewMode,
    setSubjectViewMode: s.setSubjectViewMode,
    updateTytSubject: s.updateTytSubject,
    updateAytSubject: s.updateAytSubject,
    bulkMasterTytSubjectsByName: s.bulkMasterTytSubjectsByName,
    bulkMasterAytSubjectsByName: s.bulkMasterAytSubjectsByName,
    addFailedQuestion: s.addFailedQuestion,
    solveFailedQuestion: s.solveFailedQuestion,
    removeFailedQuestion: s.removeFailedQuestion,
    isDevMode: s.isDevMode,
    failedQuestions: s.failedQuestions,
    migrateLegacyChat: s.migrateLegacyChat,
    user: s.authUser,
    signOut: s.signOut,
    isZenMode: s.isZenMode,
    setZenMode: s.setZenMode,
    ambienceType: s.ambienceType,
    setAmbienceType: s.setAmbienceType,
    ambienceVolume: s.ambienceVolume,
    setAmbienceVolume: s.setAmbienceVolume,
    isTtsEnabled: s.isTtsEnabled,
    setTtsEnabled: s.setTtsEnabled,
    recomputeFullElo: s.recomputeFullElo,
    recomputeStreak: s.recomputeStreak,
  })));
};
